ARG GO_VERSION=1.24.0

FROM ghcr.io/loong64/golang:${GO_VERSION}-trixie AS unified-builder

RUN apt-get update && \
    apt-get install -y ca-certificates ccache cmake pigz && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ARG APP_VERSION

ARG WORKDIR=/go/src/github.com/ollama/ollama
RUN git clone -b ${APP_VERSION} --depth=1 https://github.com/ollama/ollama ${WORKDIR}

ENV LDFLAGS=-s

WORKDIR ${WORKDIR}

ADD loong64.patch /tmp/loong64.patch

RUN --mount=type=cache,target=/root/.ccache \
    git apply /tmp/loong64.patch && \
    cmake --preset 'CPU' && \
    cmake --build --parallel --preset 'CPU' && \
    cmake --install build --component CPU --strip --parallel 4

ENV GOARCH loong64
ENV CGO_ENABLED 1

RUN --mount=type=cache,target=/root/.cache/go-build \
    export VERSION=$(git describe --tags --first-parent --abbrev=7 --long --always | sed -e "s/^v//g") && \
    export GOFLAGS="'-ldflags=-w -s \"-X=github.com/ollama/ollama/version.Version=$VERSION\" \"-X=github.com/ollama/ollama/server.mode=release\"'" && \
    go build -trimpath -buildmode=pie -o /bin/ollama .

RUN mkdir -p dist/linux-$GOARCH/bin && \
    cp /bin/ollama dist/linux-$GOARCH/bin/ && \
    cp -r dist/lib dist/linux-$GOARCH/ && \
    cd dist/linux-$GOARCH && \
    tar -cf - . | pigz --best > ../ollama-linux-$GOARCH.tgz

FROM ghcr.io/loong64/debian:trixie-slim

WORKDIR /opt/ollama

COPY --from=unified-builder /go/src/github.com/ollama/ollama/dist/ollama-linux-*.tgz /opt/ollama/dist/

VOLUME /dist

CMD cp -rf dist/* /dist/